blank_issues_enabled: true
contact_links:
  - name: 💬 Forum
    url: https://forum.mapilio.com/
    about: Ask on Mapilio Community Forum
  - name: 🎧 Discord
    url: https://discord.com/invite/St5z2sUZ7H
    about: Ask on Mapilio Discord
