name: ❓ Question
description: Ask questions about Mapilio Toolkit
# title: " "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a Question!

  - type: textarea
    attributes:
      label: Question
      description: What is your question?
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      placeholder: Might be an idea or suggestion to improve the toolkit.
      description: Anything else you would like to share?