#!/bin/bash
set -e

OS=osx

# build
mkdir -p dist
rm -rf dist/${OS}
pyinstaller --version
pyinstaller --noconfirm --distpath dist/${OS} flask_app.spec

# check
SOURCE=dist/${OS}/MapilioKit-Flask.app/Contents/MacOS/MapilioKit-Flask
$SOURCE --version
# VERSION=$($SOURCE --version | awk '{print $1}')

echo "HELLOOOOO"
ARCH=$(uname -m)
TARGET=dist/releases/MapilioKit-Flask-${OS}-${ARCH}.zip

# package
mkdir -p dist/releases
zip -j "$TARGET" "$SOURCE"
#cp "$SOURCE" "$TARGET"
#chmod +x "$TARGET"

# sha256
TARGET_BASENAME=$(basename "$TARGET")

cd dist/releases
shasum -a256 "$TARGET_BASENAME" | tee "${TARGET_BASENAME}.sha256.txt"
cd ../../

# summary
ls -l dist/releases
