#!/bin/bash
set -e

OS=linux

# build
mkdir -p dist
rm -rf dist/${OS}
pyinstaller --version
pyinstaller --noconfirm --distpath dist/${OS} flask_app.spec

# check
SOURCE=dist/${OS}/MapilioKit-Flask
$SOURCE --version
VERSION=$($SOURCE --version | awk '{print $1}')
ARCH=$(uname -m)
TARGET=dist/releases/mapilio-kit-${VERSION}-${OS}-${ARCH}

# package
mkdir -p dist/releases
cp "$SOURCE" "$TARGET"

# sha256
TARGET_BASENAME=$(basename "$TARGET")
cd dist/releases
shasum -a256 "$TARGET_BASENAME" | tee "${TARGET_BASENAME}.sha256.txt"
cd ../../

# summary
ls -l dist/releases