#!/bin/bash
set -e

OS=linux

# build
mkdir -p dist
rm -rf dist/${OS}
pyinstaller --version
pyinstaller --noconfirm --distpath dist/${OS} flask_app.spec

# check
SOURCE=dist/${OS}/MapilioKit-Flask

nohup $SOURCE --version > /dev/null 2>&1 &
PID=$!

sleep 5

VERSION=$($SOURCE --version | awk '{print $1}')
ARCH=$(uname -m)
TARGET=dist/releases/mapilio-kit-${VERSION}-${OS}-${ARCH}

# package
mkdir -p dist/releases
cp "$SOURCE" "$TARGET"

# sha256
TARGET_BASENAME=$(basename "$TARGET")
cd dist/releases
shasum -a 256 "$TARGET_BASENAME" | tee "${TARGET_BASENAME}.sha256.txt"
#ZIP_FILE=mapilio-kit-${VERSION}-${OS}-${ARCH}.zip
#zip -r "$ZIP_FILE" .
find . -mindepth 1 ! -name '*.txt' -delete


cd ../../

kill $PID

# summary
ls -l dist/releases
