# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    branches: [flask_app]
  push:
    branches: [flask_app]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        # Optional - x64 or x86 architecture, defaults to x64
        # architecture: "x64"

    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        working-directory: ./main

    steps:
      # https://github.com/actions/checkout#Checkout-multiple-repos-side-by-side
      # pull
      - uses: actions/checkout@v4
        with:
          path: main

      # https://github.com/actions/checkout#Checkout-multiple-repos-side-by-side
      - name: Setup ExifTool
        uses: actions/checkout@v4
        with:
          repository: "exiftool/exiftool"
          path: exiftool

      - name: Check ExifTool version
        # https://exiftool.org/install.html
        run: |
          mv ${{ github.workspace }}/exiftool/exiftool ${{ github.workspace }}/exiftool/exiftool.pl
          perl ${{ github.workspace }}/exiftool/exiftool.pl -ver

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        if: matrix.platform != 'macos-latest'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install -r requirements-dev.txt

      - name: Test with pytest
        run: |
          mapilio_kit --version
          pytest -s -vv tests
        env:
          MAPILIO_KIT__TESTS_EXECUTABLE: mapilio-kit
          MAPILLARY_TOOLS__TESTS_EXIFTOOL_EXECUTABLE: perl ${{ github.workspace }}/exiftool/exiftool.pl