name: Python package

on:
  pull_request:
    branches: [flask_app]
  push:
    branches: [flask_app]

jobs:
  build:
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        working-directory: ./main

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Setup ExifTool
        uses: actions/checkout@v4
        with:
          repository: "exiftool/exiftool"
          path: exiftool

      - name: Check ExifTool version
        run: |
          mv ${{ github.workspace }}/exiftool/exiftool ${{ github.workspace }}/exiftool/exiftool.pl
          perl ${{ github.workspace }}/exiftool/exiftool.pl -ver

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        if: matrix.platform != 'macos-latest'

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install . || true

      - name: Verify installed packages
        run: python -m pip freeze

      - name: Create directory if not exists
        run: mkdir -p build/bdist.macosx-10.9-universal2/wheel/mapilio_kit

      - name: Copy __init__.py file
        run: cp build/lib/mapilio_kit/__init__.py build/bdist.macosx-10.9-universal2/wheel/mapilio_kit || true

      - name: Test with pytest
        run: |
          mapilio_kit --version
          pytest -s -vv tests
        env:
          MAPILIO_KIT__TESTS_EXECUTABLE: mapilio-kit
          MAPILIO_KIT__TESTS_EXIFTOOL_EXECUTABLE: perl ${{ github.workspace }}/exiftool/exiftool.pl
